Add plex
truenas/apps pull request #11
Opened 2024-06-04 14:24 UTC by stavros-k

2024-06-05 13:22 UTC, stavros-k commented on ix-dev/charts/plex/app.yaml
> +train: charts
I think it was simplifying the validation, but will be better to let @sonicaj explain.

2024-07-24 15:29 UTC, sonicaj requested changes
Migration is not executable and you are missing shebang as well which would result in it not executing

2024-07-24 15:33 UTC, stavros-k commented
> Migration is not executable and you are missing shebang as well which would result in it not executing

We had validations in place for that on charts. Fixed for now, we should re-add the validation on apps too!

2024-07-29 13:30 UTC, Qubad786 approved these changes

2024-07-29 13:30 UTC, Qubad786 commented on ix-dev/stable/plex/templates/docker-compose.yaml
> +  "plex_image": "plexinc/pms-docker:1.40.2.8395-c67dce28e",
How are image updates going to be handled?

2024-07-29 16:37 UTC, sonicaj approved these changes

2024-07-29 16:38 UTC, merged