First draft for LMS app
truenas/apps pull request #1243
Opened 2024-12-26 21:18 UTC by hartzell

First draft for an app for the Lyrion Music Server (used to be Logitech Music Server).

Bits stolen from flaresolverr (extant app) and Parsonlabs Music (MR), chosen at random.

With the values in the `basic-values.yaml` test inputs file, this seems to work.

If I hack those answers up a bit and mount a real tree full of music into the volume then I can even index music.

I need to get some feedback from the ixSystems folks.

TODO:
- make port adjustable
- screenshots

2025-01-02 15:22 UTC, stavros-k commented
Hello, I'll take a look shortly.

Regarding the permissions, this is only needed when the container runs rootless.
In this case the container runs as root, and the sub processes of it run rootless. Still the pid 1 runs as root.
Eg if you see the upstream dockerfile https://github.com/LMS-Community/slimserver-platforms/blob/9c80a1dc89d8ec42dad5a7b28321c6db172d911b/Docker/start-container.sh#L5-L10

at startup it will create the user/group based on the PUID/PGID and then fix the permissions itself.

2025-01-02 15:33 UTC, hartzell commented
Thank you!

2025-01-02 15:45 UTC, stavros-k requested changes
Thanks for the contribution! Left few comments.!
Overall looks fine, just small nits here and there.

Once those are fixed, I'll take a closer look as well!
Thansk!

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/app.yaml
> +  url: https://github.com/hartzell
Please use the ix systems as maintainer here.

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/app.yaml
> +name: lms
Lets rename it to `lyrion-music-server` (also remember to rename the directory)

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/app.yaml
> +  user_name: lms
This should say root, as the main pid is running as root

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/ix_values.yaml
> +  run_as_group: 568
No need to add those as constants, they are configurable

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/questions.yaml
> +
we need a run as section here

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/templates/docker-compose.yaml
> +{% do c1.environment.add_env("PGID", values.consts.run_as_group) %}
once you add the run_as section in both the test file and the questions, you wont need those. it will pick it up automatically

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/templates/docker-compose.yaml
> +{% do c1.healthcheck.set_test("curl", {"port": values.network.web_port, "path": "/"}) %}
```suggestion
{% do c1.healthcheck.set_test("curl", {"port": values.network.web_port}) %}
```
`/` is the default

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/templates/test_values/basic-values.yaml
> +music:
```suggestion
lms:
```

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/templates/docker-compose.yaml
> +{% do c1.environment.add_env("PGID", values.consts.run_as_group) %}
also add the line to add additional env variables.

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/templates/docker-compose.yaml
> +{% do c1.environment.add_env("PGID", values.consts.run_as_group) %}
```suggestion
{% do c1.environment.add_env("PGID", values.consts.run_as_group) %}
{% do c1.environment.add_env("HTTP_PORT", values.network.web_port.port_number) %}
```

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/templates/docker-compose.yaml
> +{% do c1.environment.add_env("PGID", values.consts.run_as_group) %}
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/aeb19b8f-3193-4d06-8881-097f791bb940" />

The cli port is gonna be a problem at some point tho.

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/questions.yaml
> +              - definitions/port
```suggestion
        - variable: web_port
          label: WebUI Port
          schema:
            type: dict
            attrs:
              - variable: bind_mode
                label: Port Bind Mode
                description: |
                  The port bind mode.</br>
                  - Publish: The port will be published on the host for external access.</br>
                  - Expose: The port will be exposed for inter-container communication.</br>
                  - None: The port will not be exposed or published.</br>
                  Note: If the Dockerfile defines an EXPOSE directive,
                  the port will still be exposed for inter-container communication regardless of this setting.
                schema:
                  type: string
                  default: "published"
                  enum:
                    - value: "published"
                      description: Publish port on the host for external access
                    - value: "exposed"
                      description: Expose port for inter-container communication
                    - value: ""
                      description: None
              - variable: port_number
                label: Port Number
                schema:
                  type: int
                  show_if: [["bind_mode", "!=", ""]]
                  default: 31101
                  required: true
                  $ref:
                    - definitions/port
```

This is the new format for port

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/questions.yaml
> +              - definitions/port
```suggestion
        - variable: cli_port
          label: CLI port
          schema:
            type: dict
            attrs:
              - variable: bind_mode
                label: Port Bind Mode
                description: |
                  The port bind mode.</br>
                  - Publish: The port will be published on the host for external access.</br>
                  - Expose: The port will be exposed for inter-container communication.</br>
                  - None: The port will not be exposed or published.</br>
                  Note: If the Dockerfile defines an EXPOSE directive,
                  the port will still be exposed for inter-container communication regardless of this setting.
                schema:
                  type: string
                  default: "published"
                  enum:
                    - value: "published"
                      description: Publish port on the host for external access
                    - value: "exposed"
                      description: Expose port for inter-container communication
                    - value: ""
                      description: None
              - variable: port_number
                label: Port Number
                schema:
                  type: int
                  show_if: [["bind_mode", "==", "published"]]
                  default: 9090
                  required: true
                  $ref:
                    - definitions/port
```

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/templates/docker-compose.yaml
> +{% do c1.ports.add_port(3483, 3483, {"protocol": "udp"}) %}
```suggestion
{% do c1.add_port(values.network.web_port) %}
{# TODO: We might have to expose the container port as well on ui #}
{% do c1.add_port(values.network.cli_port, {"container_port": 9090}) %}
{# FIXME: those should be exposed on UI too, and use the c1.add_port() #}
{% do c1.ports.add_port(3483, 3483) %}
{% do c1.ports.add_port(3483, 3483, {"protocol": "udp"}) %}
```
Left couple todo's. I'll check them later

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/app.yaml
> +categories:
currently ui supports only 1 category

2025-01-02 15:45 UTC, stavros-k commented on ix-dev/community/lms/app.yaml
> +capabilities: []
Missing the capabilities here (chown, etc)

2025-01-04 23:07 UTC, hartzell commented on ix-dev/community/lms/templates/docker-compose.yaml
> +{% do c1.environment.add_env("PGID", values.consts.run_as_group) %}
Added your suggestion.  Scratching head a bit about the CLI port "problem", will revisit this comment after working through the other PORT bits below.

2025-01-04 23:09 UTC, hartzell commented on ix-dev/community/lms/questions.yaml
> +              - definitions/port
Done, but used 9000 as default, not the 31101 in your change.  Am I mis-understanding?

2025-01-04 23:13 UTC, hartzell commented on ix-dev/community/lms/templates/docker-compose.yaml
> +{% do c1.ports.add_port(3483, 3483, {"protocol": "udp"}) %}
Done, left the TODO/FIXME's in place

2025-01-04 23:14 UTC, hartzell commented on ix-dev/community/lms/app.yaml
> +categories:
done, went with "media"

2025-01-04 23:16 UTC, hartzell commented on ix-dev/community/lms/app.yaml
> +capabilities: []
done

2025-01-05 01:20 UTC, hartzell commented
@stavros-k -- I think I've addressed your feedback (assuming I did the right thing with the web port bit I left unresolved above).  I can run the server using the generated docker-compose.yaml and it seems to work (haven't fed it any real streams or music yet though).

2025-01-05 16:34 UTC, hartzell commented
For screenshots, how about

- https://lyrion.org/assets/screenshot.png

2025-01-07 11:02 UTC, stavros-k commented on ix-dev/community/lyrion-music-server/app.yaml
> +- description: Main pid runs as root
```suggestion
- description: Lyrion Music Server runs as root user.
```

2025-01-07 11:06 UTC, stavros-k reviewed
Looks mostly good. Will check the port thingies in a bit and update the url for the images

2025-01-07 11:06 UTC, stavros-k commented on ix-dev/community/lyrion-music-server/ix_values.yaml
> +
```suggestion
```

2025-01-07 11:06 UTC, stavros-k commented on ix-dev/community/lyrion-music-server/templates/test_values/basic-values.yaml
> +  playlist: /mnt/storage/lms/playlist
```suggestion
  config: /opt/tests/mnt/storage/lms/config
  music: /opt/tests/mnt/storage/lms/music
  playlist: /opt/tests/mnt/storage/lms/playlist
```

2025-01-07 11:06 UTC, stavros-k commented on ix-dev/community/lyrion-music-server/templates/test_values/basic-values.yaml
> +  playlist: /mnt/storage/lms/playlist
Mostly to keep it consistent with the rest.
I dont want someone to accidentaly run the tests and files in their /mnt/storage are getting written/overwritten

2025-01-07 11:06 UTC, stavros-k commented on ix-dev/community/lyrion-music-server/questions.yaml
> +
missing the `variable: lms` section with the addtitional envs section

2025-01-07 11:06 UTC, stavros-k commented on ix-dev/community/lyrion-music-server/questions.yaml
> +  - name: Network Configuration
Missing the user group here

2025-01-07 11:07 UTC, stavros-k commented
> For screenshots, how about
> 
>     * https://lyrion.org/assets/screenshot.png
> 
> 
> And for an icon:
> 
>     * https://raw.githubusercontent.com/LMS-Community/slimserver-platforms/public/9.0/win32/res/SqueezeCenter.ico

Does the app have a webgui? or is it a server only?
If its a server only, I dont think we should add a screenshot of the client here.

2025-01-07 11:27 UTC, stavros-k commented on ix-dev/community/lyrion-music-server/app.yaml
> +icon: https://avatars.githubusercontent.com/u/138057124?s=200&v=4
```suggestion
icon: https://media.sys.truenas.net/apps/lyrion-music-server/icons/icon.png
```

2025-01-08 15:57 UTC, hartzell commented on ix-dev/community/lyrion-music-server/ix_values.yaml
> +
done

2025-01-08 16:08 UTC, hartzell commented on ix-dev/community/lyrion-music-server/templates/test_values/basic-values.yaml
> +  playlist: /mnt/storage/lms/playlist
Is there a standard way to get `/opt/tests` set up on a TrueNAS Scale system?  `/opt` is on the boot-pool, which is read-only.  I've seen references to remounting it r/w, but also warnings that that's not supported (might lead Support to ignoring questions).

2025-01-08 16:11 UTC, hartzell commented on ix-dev/community/lyrion-music-server/questions.yaml
> +  - name: Network Configuration
done

2025-01-08 16:14 UTC, hartzell commented on ix-dev/community/lyrion-music-server/questions.yaml
> +
done.

2025-01-08 16:15 UTC, stavros-k commented on ix-dev/community/lyrion-music-server/templates/test_values/basic-values.yaml
> +  playlist: /mnt/storage/lms/playlist
Those paths are picked for local development. ie your laptop/pc
Specifically the /opt/tests are picked because macOS whitelists those by default
(https://github.com/truenas/apps/blob/master/CONTRIBUTIONS.md#appyaml)

2025-01-08 16:16 UTC, hartzell commented
@stavros-k asked:
> Does the app have a webgui? or is it a server only?

Yes, it does, unless I mis-understand your question.  The image at:

> https://lyrion.org/assets/screenshot.png

is the main page of what LMS serves on the `web_port`, port 9000.

2025-01-08 16:18 UTC, hartzell commented on ix-dev/community/lyrion-music-server/app.yaml
> +icon: https://avatars.githubusercontent.com/u/138057124?s=200&v=4
done

2025-01-08 16:23 UTC, hartzell commented on ix-dev/community/lyrion-music-server/templates/test_values/basic-values.yaml
> +  playlist: /mnt/storage/lms/playlist
Yep, I saw that.  But, I'm not doing this work on my laptop, I'm doing it on my TrueNAS scale system.  Those paths are particularly problematic on a Scale box.

I'd happily just carve off a data set from my storage pool, but I don't see any supported way to mount it on /opt/tests.  Trying to to go wandering off into the forest if I can help it.

Any Scale suggestions?

2025-01-08 16:24 UTC, stavros-k commented on ix-dev/community/lms/questions.yaml
> +              - definitions/port
I prefer to have unique ports across apps, to avoid conflicts.

2025-01-08 16:28 UTC, stavros-k commented on ix-dev/community/lyrion-music-server/app.yaml
> +sources:
```suggestion
screenshots:
- https://media.sys.truenas.net/apps/lyrion-music-server/screenshots/screenshot1.png
sources:
```

2025-01-08 16:29 UTC, stavros-k commented
I'll take a look on the cli port thingy later today and update the library. And merge it afterwards!
Nice work!

2025-01-08 16:29 UTC, hartzell commented on ix-dev/community/lms/questions.yaml
> +              - definitions/port
If I understand correctly, something else already has 9000 so you're using something else here, but nothing else has 9090 so you used that for the cli port.
If that's correct, I'll change 9000 -> 31101.

Is there a place to warn people that, unless they take action, LMS will end up running on a non-traditional port?

2025-01-08 16:35 UTC, hartzell commented
Thank you for all your help!

2025-01-08 16:40 UTC, stavros-k commented on ix-dev/community/lyrion-music-server/templates/test_values/basic-values.yaml
> +  playlist: /mnt/storage/lms/playlist
Developing apps on scale is not really easy. Well at least I don't find it easy.
Changing the paths during dev is fine. But I think most people will use their computers to do dev.
Hence insisting on keeping the paths under /opt/tests/

2025-01-09 14:47 UTC, stavros-k commented
@hartzell  
Looks like you have dis-allowed changes to be pushed on this PR.
I have found solutions for the cli port, can you open it so I can push them?

2025-01-09 15:11 UTC, hartzell commented
I'm happy to give you access, but I can't figure out how.

[This page](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) says there should be a click box on the PR, but I don't see it where they describe or anywhere else.

Can you describe to me how to do this?

2025-01-09 15:15 UTC, stavros-k commented
It should be on the right side of this PR 
<img width="1402" alt="image" src="https://github.com/user-attachments/assets/49b5c1a4-2108-4338-b563-e81e984ff29e" />

Under the lock conversation. Is it there?

2025-01-09 15:18 UTC, hartzell commented
Don't see it.  Are you officially a "maintainer" for this repo?

<img width="399" alt="Screenshot 2025-01-09 at 8 17 19 AM" src="https://github.com/user-attachments/assets/f7f9da6a-368e-462f-9dcb-542dc9958e41" />

2025-01-09 15:20 UTC, stavros-k commented
Yea, I was able to edit PRs on the past.
I'll send you the patch then so you can apply

2025-01-09 15:22 UTC, stavros-k commented
> Weird. I spend most of my work time in GItLab, so I haven't kept up with the _Hub_ UI. Sorry if I'm missing it.

No, you are not missing it. it should be there. I'll check repo settings later as well.
Sending you the patch in a bit

2025-01-09 15:24 UTC, hartzell commented
I might be causing it, it seems like the behavior is different if the fork belongs to an individual or an org.  I created an "org" (hartzell-forks) as a place to keep my forks so they don't get mixed in with my stuff.  Neat freak, etc...

At least that's what this PR suggests might be happening: https://github.com/orgs/community/discussions/9921

2025-01-09 15:32 UTC, stavros-k commented
[0001-polish-app.patch](https://github.com/user-attachments/files/18363652/0001-polish-app.patch)

2025-01-09 15:33 UTC, hartzell commented
I'll apply the patch and push, thank you.

Looks like it's not possible to set up, https://github.com/orgs/community/discussions/5634, even comments from other folks who use an org to manage their forks.  Sigh....

2025-01-09 15:34 UTC, stavros-k commented
Oh well. Now we know :D Thanks for looking for that info!

2025-01-09 15:41 UTC, hartzell commented
Applied.
This seems to work for me (once I adjust the test dirs)
```
.github/scripts/ci.py --app lyrion-music-server --train community --test-file basic-values.yaml
```

2025-01-09 15:57 UTC, stavros-k commented on ix-dev/community/lyrion-music-server/app.yaml
> +lib_version: 2.1.8
can you either update the library files or changed it back ot 2.1.7 and I'll update to another PR

2025-01-09 16:15 UTC, hartzell commented on ix-dev/community/lyrion-music-server/app.yaml
> +lib_version: 2.1.8
Rebased to the tip of master, reran the `.github/... command`, git rm'd the 2.1.7 lib and added the 2.1.8 lib.

Hopefully that's what you need.

2025-01-09 16:42 UTC, stavros-k approved these changes

2025-01-09 16:43 UTC, merged

2025-01-09 17:51 UTC, hartzell commented
Thank you for all the help!

2026-03-05 17:28 UTC, hartzell commented
Hi @stavros-k -- I haven't been using this app since the airplay plugin that I depend on wasn't working in the container environment.  Has anything changed with regard to app networking capabilities in the past year?  In the freebsd jail world I'd just set up an independent network stack.  I'm not sure if there's something analogous here.